from redis import StrictRedis

redis = StrictRedis(host='localhost', port=6379, db=0, password=None)
redis.set('name','Gowther')
redis.set('age',24)
redis.set('height',174)
redis.set('address','Shanghai')
# print(redis.get('name'))
# print(redis.exists('name'))
# redis.delete('name')
# print(redis.exists('name'))
# print(redis.type('age'))
# print(redis.type('name'))
# print(redis.keys('a*'))
# print(redis.randomkey())
# print(redis.dbsize())
# redis.flushdb()
# print(redis.dbsize())
print(redis.mget(['name','age']))
print(redis.get('age'))
redis.incr('age',1)
print(redis.get('age'))
redis.append('address','minhang')
print(redis.get('address'))